== Функциональные требования

|====
|*Система* |*Модуль* |*Список требований*|*Бизнес-цель*

|Каталог товаров
|-
|1. Система хранит информацию о товарах по категориям, а также необходимые характеристики по каждому товару. Набор характеристик может расширяться +
2. Спортсмен/Инструктор имеет возможность просматривать каталог товаров с постраничной выдачей и информацию по каждому товару в мобильном приложении и веб-интерфейсе +
3. Спортсмен/Инструктор имеет возможность поиска товаров по различным фильтрам (в соответстви с заданными характеристиками), включая полнотекстовый поиск в мобильном приложении и веб-интерфейсе +
4. Менеджер формирует акции в отдельном веб-интерфейсе. Акции предосталяются на товары по категориям или по определенным характеристикам, например по региону. Менеджер настраивает параметры уведомления по акции +
5. Система формирует и отправляет уведомление спортсменам о новых товарах в систему Уведомления +
6. Система формирует и отправляет уведомление спортсменам о новых акциях в систему Уведомления +
|1, 2

|Приложение для покупки товаров
|-
|1. Спортсмен/Инструктор имеет возможность поиска товаров по различным фильтрам (в соответстви с заданными характеристиками товара), включая полнотекстовый поиск  +
2. Спортсмен/Инструктор имеет возможность создания заказа на выбранные товары. Один заказ может содержать не более 30 товаров +
3. Спортсмен/Инструктор имеет возможность оплаты товаров онлайн через встроенный платежный модуль
|2

|Тренировки
|План тренировки
|1. Инструктор имеет возможность создания/редактирования описания тренировки, созданной им. +
2. Инструктор имеет возможность создания списка требуемого инвентаря и одежды для тренировки из Каталога товаров +
3. Инструктор имеет возможность создания/прикрепления видео тренировки +
4. Система формирует и отправляет уведомление спортсменам о новом плане тренировки в систему Уведомления
|1, 2, 3

|Тренировки
|Расписание тренировок
|1. Спортсмен/Инструктор имеет возможность создания расписания тренировок на основе выбранных планов тренировок +
2. Спортсмен/Инструктор имеет возможность создания расписания групповых тренировок, пригласив Спортсменов в группу +
3. Система отправляет в мобильное приложение напоминание о начале тренировки за день и за 1 час  до начала тренировки
|1, 3

|Тренировки
|Результаты тренировок
|1. Спортсмен  имеет возможность сохранения результатов тренировки, введенных вручную. +
2. Система выполняет сравнение результатов проведенных тренировок и отображает в отдельном разделе приложения. Спортсмен может выбирать, по каким параметрам сравнивать результаты тренировки.
|1

|Пользователи
|-
|1. Спортсмен/Администратор имеет возможность сохранения/редактирования информации о пользователе +
2. Система использует данные о пользователе на основе существующего данных Приложения для покупки товаров
|1

|Внешнее приложение для сбора показателей тренировки
|-
|1. Мобильное приложение имеет интеграцию с внешним приложением для сбора показателей нагрузки спортсмена: Пульс, количество шагов, количество сожженных калорий
|1, 3

|Соревнования
|-
|1. Спортсмен имеет возможность создания соревнования с данными о нем (вид спорта, место, время, программа, требования к спортсмену) +
2. Спортсмен имеет возможность выбора соревнования для участия +
2. Система фиксирует результаты соревнований спортсменов
|1, 3

|Соревнования
|TOP-5
|1. Система формирует и отправляет уведомление спортсменам, примавшим участие в соревновании, о 5 лучших результатах соревнований
|1, 3

|Социальные группы
|-
|1. Спортсмен/Инструктор имеет возможность создания собственного тематического канала +
2. Спортсмен/Инструктор формирует приглашения в канал по виду спорта +
3. Спортсмены/Инструкторы обмениваются сообщениями в тематическом канале
|1, 3
|====
